print("\n\tPERSEGI")
sisi = int(input("Masukkan sisi\t\t\t : "))
print("\n\tPERSEGI PANJANG")
panjang = int(input("Masukkan panjang\t\t : "))
lebar = int(input("Masukkan lebar\t\t\t : "))
print("\n\tTRAPESIUM")
tinggi = int(input("Masukkan tinggi trapesium\t : "))
AB = int(input("Masukkan sisi AB\t\t : "))
BC = int(input("Masukkan sisi BC\t\t : "))
CD = int(input("Masukkan sisi CD\t\t : "))
DA = int(input("Masukkan sisi DA\t\t : "))
print("\n\tLUAS DAN KELILING")
print("Luas Persegi \t\t\t : ", sisi*sisi)
print("Keliling Persegi \t\t : ", sisi*4)
print("Luas Persegi Panjang \t\t : ", panjang*lebar)
print("Keliling Persegi Panjang\t : ", (panjang*2)+(lebar*2))
print("Luas Trapesium \t\t\t : ", tinggi*(AB+CD)/2)
print("Keliling Trapesium \t\t : ", AB + BC + CD + DA)