print("PROGRAM MENGHITUNG VOLUME TABUNG DAN BALOK")

print("TABUNG")
la=int(input("masukkan luas alas:"))
t= int(input("masukan tinggi:"))
print("\n")
print("BALOK")
p=int(input("masukkan panjang:"))
l=int(input("masukkan lebar:"))
t=int(input("masukkan tinggi:"))
print("\n")
print("HASIL")
print("volume tabung:",la*t)
print("volume balok:",p*l*t)